### ISSUE TITLE
Make server configurable using config-rs

### ISSUE THREAD

**Issue by llucax** [noclick-me/noclickd#3]
https://crates.io/crates/config

**Comment by vbmade2000** [comment]
Do you have a preference for format (TOML, JSON, etc)?

**Comment by llucax** [comment]
Hi Malhar! Yes, toml or yaml is OK, I don't find JSON ideal for config because of the lack of comments and other minor annoyances (like having a trailing comma being a syntax error).

**Comment by llucax** [comment]
Using environment variables via a `.env` file can also be an option, which is quite convenient for deploying with k8s.

**Comment by vbmade2000** [comment]
Then I think I would go for TOML with the config file option. Anyways, we can change it later if required.

**Comment by llucax** [comment]
Yeah, TOML sounds good, thanks!

**Comment by llucax** [comment]
If you are really going for it (that would be awesome), I can assign you. Just let me know if I should :)

**Comment by vbmade2000** [comment]
While trying to run, it throws following.
```
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/vbmade2000/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.9/src/pool/inner.rs:327:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.

```

**Comment by llucax** [comment]
Hi @vbmade2000, unfortunately I couldn't find much time to try this myself. You get this trying to build the project from scratch or did you add any new dependencies?

**Comment by vbmade2000** [comment]
I didn't add anything new except config-rs but I upgraded actix-web to 4-rc. Yes I faced this issue while building the project.

**Comment by llucax** [comment]
I see. I don't know what kind of interactions are between config-rs and the current dependencies. From my side feel free to upgrade any dependencies

**Comment by vbmade2000** [comment]
I think it is because of mismatch in versions of tokio used actix and some other package. Still not entirely sure.

**Comment by vbmade2000** [comment]
Ah it is because of upgrading `sqlx` from 0.4.2 to 0.5.11. Possibly due to tokio version change. I'll raise a PR to revert back to 0.4.2 for now. I learned from this mistake, to run application even if you think that your changes are not going to affect run of a program.

**Comment by llucax** [comment]
Alright! Yeah, unfortunately dependencies are very fragile and is easy to get into these situations, specially when libraries are not very mature (which is usually the case in Rust).

**Comment by vbmade2000** [comment]
```
#[derive(Debug, Deserialize)]
pub struct CorsConfig {
    pub allowed_origins: Vec<String>,
    pub allowed_methods: Vec<Method>,
    pub allowed_headers: Vec<HeaderName>,
}
```
In above code in `config.rs`, `Method` and `HeaderName` are not deserializable by default. I used a macro developed by my colleague who implements `Serialize/Deserialize` for string types. It requires local type. Like for Method I created 

pub struct HttpMethhod(pub Method) wrapper type and used it like `pub allowed_methods: Vec<HttpMethod>,` but it could be complicated as may be in many places `Method` type is used. So it could be complicated.

If you know some easy way to resolve this issue then we can use that otherwise I can go with above mentioned approach.

**Comment by vbmade2000** [comment]
Never mind. I found another way to solve the problem.

**Comment by vbmade2000** [comment]
Can we close this or something is still pending?

**Comment by llucax** [comment]
Yup, next time if you included "Fixes #<issue>" in the PR description, it will close the associated issue automatically when the PR is merged.
